const fs = require('fs');
const path = require('path');
const base = 'C:/Users/MARCHlnwza/Desktop/wed com';

// 1. Update checkout.js to POST order to backend API
let checkoutPath = path.join(base, 'checkout.js');
let checkoutCode = fs.readFileSync(checkoutPath, 'utf-8');

// Find the block where order is saved to localStorage (around line with 'localStorage.setItem('orders'')
const orderSaveRegex = /localStorage\.setItem\('orders',\s*JSON\.stringify\(orders\)\);/;
if (orderSaveRegex.test(checkoutCode)) {
  const replacement = `
    // Send order to backend API (MongoDB)
    fetch('http://localhost:5000/api/orders', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
            // id will be generated by backend if you want, but keep client‑side for now
            items: cart,
            total: total,
            address: addr,
            payment: chkMethod.value,
            status: 'Processing',
            date: new Date().toISOString()
        })
    })
    .then(r => r.json())
    .then(data => {
        console.log('Order saved to DB', data);
    })
    .catch(err => console.error('Failed to save order', err));
    // Also keep local copy for quick UI reference (optional)
    const orders = JSON.parse(localStorage.getItem('orders')) || [];
    orders.push({
        id: data.id || 'ORD' + Math.floor(Math.random()*1000000),
        date: new Date().toISOString(),
        total: total,
        items: cart,
        status: 'Processing',
        address: addr,
        payment: chkMethod.value
    });
    localStorage.setItem('orders', JSON.stringify(orders));
`; // note: we cannot use data variable outside promise, will adjust below

  // We'll replace the line with a comment placeholder and later adjust code manually
  checkoutCode = checkoutCode.replace(orderSaveRegex, '// ORDER SAVED VIA API (see below)');
  // Insert new code just after the placeholder comment (find its index)
  const placeholder = '// ORDER SAVED VIA API (see below)';
  const insertIdx = checkoutCode.indexOf(placeholder) + placeholder.length;
  checkoutCode = checkoutCode.slice(0, insertIdx) + `\n${replacement}\n` + checkoutCode.slice(insertIdx);
  fs.writeFileSync(checkoutPath, checkoutCode);
  console.log('checkout.js updated to send orders to API');
} else {
  console.log('checkout.js order saving pattern not found – manual edit may be needed');
}

// 2. Update admin.js renderOrders to fetch from API instead of localStorage
let adminPath = path.join(base, 'admin.js');
let adminCode = fs.readFileSync(adminPath, 'utf-8');

// Replace the function renderOrders definition
const renderOrdersPattern = /function renderOrders\(\) \{[\s\S]*?\}/;
const newRenderOrders = `function renderOrders() {
    const tbody = document.getElementById('adminOrderList');
    if (!tbody) return;
    tbody.innerHTML = '';
    // Fetch orders from backend API
    fetch('http://localhost:5000/api/orders')
        .then(r => r.json())
        .then(orders => {
            orders.forEach(order => {
                const tr = document.createElement('tr');
                tr.innerHTML =
                    '<td>' + order.id + '</td>' +
                    '<td>' + new Date(order.date).toLocaleString() + '</td>' +
                    '<td>$' + order.total.toFixed(2) + '</td>' +
                    '<td>' + order.status + '</td>' +
                    '<td>' + (order.status !== "Confirmed" ? '<button class="action-btn confirm" data-id="' + order.id + '">Confirm</button>' : '') + '</td>';
                tbody.appendChild(tr);
            });
            // Bind confirm buttons after rendering
            document.querySelectorAll('.action-btn.confirm').forEach(btn => {
                btn.addEventListener('click', e => {
                    const id = e.currentTarget.getAttribute('data-id');
                    confirmOrder(id);
                });
            });
        })
        .catch(err => console.error('Failed to load orders', err));
}`;
adminCode = adminCode.replace(renderOrdersPattern, newRenderOrders);

// Ensure confirmOrder still updates DB via PATCH
const confirmOrderPattern = /function confirmOrder\(id\) \{[\s\S]*?\}/;
const newConfirmOrder = `function confirmOrder(id) {
    // Update status via backend API
    fetch('http://localhost:5000/api/orders/' + id + '/confirm', {
        method: 'PATCH'
    })
        .then(r => r.json())
        .then(() => renderOrders())
        .catch(err => console.error('Failed to confirm order', err));
}`;
adminCode = adminCode.replace(confirmOrderPattern, newConfirmOrder);

fs.writeFileSync(adminPath, adminCode);
console.log('admin.js updated to fetch orders from API and confirm via PATCH');
